sudo: false
language: c++
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      packages:
        - cmake
        - cmake-data
        - g++-7
script: mkdir ./build && cd ./build/ && cmake .. && cmake --build .